name: RDF Wrapping CI

on:
  # Build pull requests for any branch
  pull_request: { }

permissions: {}

jobs:
  build:
    name: Java environment
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17, 21 ]

    steps:
      - uses: actions/checkout@v7

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Build the code with Maven
        run: mvn -B -ntp verify javadoc:javadoc

  sonar:
    name: SonarCloud Analysis
    permissions:
      contents: read
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v7

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'

      - name: Build and analyze with SonarCloud
        run: mvn -B -ntp verify sonar:sonar -Dsonar.token=${{ secrets.SONARQUBE_TOKEN }}

  check:
    permissions: {}
    if: always()
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # release/v1
        with:
          jobs: ${{ toJSON(needs) }}
